### ISSUE TITLE
Speeding up NeRF & skipping steps

### ISSUE THREAD

**Issue by zimonitrome** [yerfor/GeneFace#16]
Hello. Currently the inference is quite slow as [pointed out in the readme](https://github.com/yerfor/GeneFace#:~:text=The%20inference%20process,NeRF%2Dbased%20renderer.).

Would it be possible to skip the Torso-NeRF, skip the background compositing, and maybe only render a small region of interest of the Head-NeRF for custom compositing in 3rd party software?

**Comment by yerfor** [comment]
Hi, apart from the two ways mentioned in README, there are two additional options:

- only render the head part, by using the `lm3d_nerf/config.yaml` instead of `lm3d_nerf_torso/config.yaml` in the inference script.
- render a smaller resolution by setting `infer_scale_factor=0.5` or a smaller value

**Comment by zimonitrome** [comment]
Thank you. I will try these out and report back!

**Comment by yerfor** [comment]
Hi, I have updated the `infer_scale_factor` to adjust the output resolution in the latest commit. Please pull the new code if you want to try `infer_scale_factor`.
