### ISSUE TITLE
Why GeneFace is taking too much time (approx 3-4 hrs ) for inference while RAD-Nerf only takes minutes (https://github.com/ashawkey/RAD-NeRF.git)

### ISSUE THREAD

**Issue by mirrorsize2022** [yerfor/GeneFace#38]

**Comment by yerfor** [comment]
Hi, the current version GeneFace uses the NeRF-based render of AD-NeRF, which is time-consuming, actually, I have planned to use RAD-NeRF as the backend of the NeRF-based render, maybe in a future release.

RAD-NeRF accelerate the inference of NeRF with several modifications on AD-NeRF:

- It uses grid-based position encoder so it models a discrete scene instead of a continuous one as AD-NeRF does.
- It use instant-ngp as the NeRF-backend, which use on torch.CPP_extension that has higher efficiency
- It use fp16 instead of fp32.

**Comment by kendo6666** [comment]
> 嗨，当前版本的 GeneFace 使用 AD-NeRF 的基于 NeRF 的渲染，这很耗时，实际上，我计划使用 RAD-NeRF 作为基于 NeRF 的渲染的后端，也许在未来的版本中。
> 
> RAD-NeRF 通过对 AD-NeRF 的一些修改加速了 NeRF 的推理：
> 
> * 它使用基于网格的位置编码器，因此它对离散场景进行建模，而不是像 AD-NeRF 那样对连续场景进行建模。
> * 它使用instant-ngp进行神经渲染，使用效率更高的torch.CPP_extension。
> * 它使用 fp16 而不是 fp32。

RAD-NeRF的确有让人惊叹的渲染速度，但是Gene的面部表情和唇形更加自然。如果Gene能改进为实时渲染就更棒了！
