### ISSUE TITLE
KeyError: 'cond_win_size'

### ISSUE THREAD

**Issue by a312863063** [yerfor/GeneFace#4]
Thanks for your amazing work! When I was running this project, I encountered an error：

Traceback (most recent call last):
  File "data_gen/nerf/binarizer.py", line 20, in <module>
    exp_cond_win_size = hparams['cond_win_size']
KeyError: 'cond_win_size'

Could you please tell me how you set 'cond_win_size' and 'smo_win_size' in your experiment? Thanks!

**Comment by yerfor** [comment]
Hi, thanks for pointing out this error! 

I have fixed it in the latest commit [9f65e71](https://github.com/yerfor/GeneFace/commit/9f65e7185dbdb41c479418c105e70ba573425b84). The error is raised because `adnerf.yaml` doesn't have a argument named `cond_win_size`. Please run `python data_gen/nerf/binarizer --config=egs/datasets/videos/May/lm3d_nerf.yaml` instead to binarize the NeRF dataset. 

By the way, we set `cond_win_size=1` and `smo_win_size=5` in `lm3d_nerf.yaml`, which we found not only preserves accurate lip-sync but also improves the temporal smoothness.
