### ISSUE TITLE
no such file

### ISSUE THREAD

**Issue by VERMANs** [yerfor/GeneFace#6]
when processing "bash scripts/infer_lm3d_nerf.sh", it said "No such file or directory: 'data/binary/videos/May/trainval_dataset.npy'"
![image](https://user-images.githubusercontent.com/41277638/217731441-efac4b3d-37ff-45d2-9c68-06f20103c3c9.png)

Can you tell me where can i find it?thanks

**Comment by yerfor** [comment]
Hi, thanks for pointing out this issue.

This bug is raised because the `data/binary/videos/May/trainval_dataset.npy`  file is missing, which is the binarized NeRF dataset for `May.mp4`. I have uploaded it at [this link](https://drive.google.com/drive/folders/1QmXCLjVw4D1wMnrXIuH3ATnCYivSNxoB?usp=share_link). Download `trainval_dataset.npy` and place it in the `data/binary/videos/May/trainval_dataset.npy` path.

In the latest commit [8f92018](https://github.com/yerfor/GeneFace/commit/8f92018feac57fc1f7904ec3e9425289e23de5fc), I have uploaded the binarized `LRS3` and `May` datasets. Please refer to `README.md` for more details!

**Comment by VERMANs** [comment]
thanks a lot!
