### ISSUE TITLE
处理好的LRS3数据集下载问题

### ISSUE THREAD

**Issue by Gpwner** [yerfor/GeneFace#68]
1、请问能否将谷歌网盘上的这个数据集切分为更小的块，比如每个文件3GB左右？可能由于网络问题，下载了好几次下载到一半就下载失败了
2、另外，这个数据有百度网盘下载链接吗？
感谢

**Comment by Gpwner** [comment]
好的，感谢大佬。

**Comment by Gpwner** [comment]
从Google网盘下载下来加压后的文件结构如下：
```

├── sizes_train.npy
├── sizes_val.npy
├── spk_id2spk_idx.npy
├── stats.npy
├── train.data
└── val.data

```

这个和你在https://github.com/yerfor/GeneFace/blob/main/docs/process_data/zh/process_lrs3-zh.md 中给出的预期目录结构不一致，是什么原因？

**Comment by yerfor** [comment]
少了idx文件，这是因为我们更新了indexed_ds 这个类，将idx也保存在了.data里面

**Comment by Hybrogen** [comment]
您好，我下载了处理好的数据集结构如下：
```
binary/lrs3
├── sizes_train.npy
├── sizes_val.npy
├── spk_id2spk_idx.npy
├── train.data
└── val.data
```
没有 `stats.npy` 这个文件，这是否表明我下的文件有损坏=w=

**Comment by Guoxni** [comment]
> 您好，我下载了处理好的数据集结构如下：
> 
> ```
> binary/lrs3
> ├── sizes_train.npy
> ├── sizes_val.npy
> ├── spk_id2spk_idx.npy
> ├── train.data
> └── val.data
> ```
> 
> 没有 `stats.npy` 这个文件，这是否表明我下的文件有损坏=w=

我也是这样，请问你可以后面可以运行吗

**Comment by azouever** [comment]
> > 您好，我下载了处理好的数据集结构如下：
> > ```
> > binary/lrs3
> > ├── sizes_train.npy
> > ├── sizes_val.npy
> > ├── spk_id2spk_idx.npy
> > ├── train.data
> > └── val.data
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 没有 `stats.npy` 这个文件，这是否表明我下的文件有损坏=w=
> 
> 我也是这样，请问你可以后面可以运行吗

我也是这样，请问你可以后面可以运行吗

**Comment by Guoxni** [comment]
我后面下载了一份别人解压好的数据进行运行的



在 2023-11-27 17:35:12，"kaixuan" ***@***.***> 写道：

您好，我下载了处理好的数据集结构如下：

binary/lrs3
├── sizes_train.npy
├── sizes_val.npy
├── spk_id2spk_idx.npy
├── train.data
└── val.data


没有 stats.npy 这个文件，这是否表明我下的文件有损坏=w=

我也是这样，请问你可以后面可以运行吗

我也是这样，请问你可以后面可以运行吗

**Comment by mj-github-github** [comment]
> 我后面下载了一份别人解压好的数据进行运行的 在 2023-11-27 17:35:12，"kaixuan" ***@***.***> 写道： 您好，我下载了处理好的数据集结构如下： binary/lrs3 ├── sizes_train.npy ├── sizes_val.npy ├── spk_id2spk_idx.npy ├── train.data └── val.data 没有 stats.npy 这个文件，这是否表明我下的文件有损坏=w= 我也是这样，请问你可以后面可以运行吗 我也是这样，请问你可以后面可以运行吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

@Guoxni Hello, 可以帮忙给个缺失文件的下载链接吗？我不知道从哪里下载

**Comment by Guoxni** [comment]
链接：https://pan.baidu.com/s/1OyYlC0_rkRJmw_0l5gE2XQ?pwd=2uyu
提取码：2uyu
找不到原作者的帖子了 这个是我的分享链接



在 2023-12-11 15:08:32，"mj-github-github" ***@***.***> 写道：

我后面下载了一份别人解压好的数据进行运行的 在 2023-11-27 17:35:12，"kaixuan" @.> 写道： 您好，我下载了处理好的数据集结构如下： binary/lrs3 ├── sizes_train.npy ├── sizes_val.npy ├── spk_id2spk_idx.npy ├── train.data └── val.data 没有 stats.npy 这个文件，这是否表明我下的文件有损坏=w= 我也是这样，请问你可以后面可以运行吗 我也是这样，请问你可以后面可以运行吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>

@Guoxni Hello, 可以帮忙给个缺失文件的下载链接吗？我不知道从哪里下载

**Comment by mj-github-github** [comment]
> 链接：https://pan.baidu.com/s/1OyYlC0_rkRJmw_0l5gE2XQ?pwd=2uyu 提取码：2uyu 找不到原作者的帖子了 这个是我的分享链接 在 2023-12-11 15:08:32，"mj-github-github" ***@***.***> 写道： 我后面下载了一份别人解压好的数据进行运行的 在 2023-11-27 17:35:12，"kaixuan" @.> 写道： 您好，我下载了处理好的数据集结构如下： binary/lrs3 ├── sizes_train.npy ├── sizes_val.npy ├── spk_id2spk_idx.npy ├── train.data └── val.data 没有 stats.npy 这个文件，这是否表明我下的文件有损坏=w= 我也是这样，请问你可以后面可以运行吗 我也是这样，请问你可以后面可以运行吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> @Guoxni Hello, 可以帮忙给个缺失文件的下载链接吗？我不知道从哪里下载 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

大佬，太感谢了！Respect

**Comment by Jiaaaaaqwe** [comment]
> 链接：https://pan.baidu.com/s/1OyYlC0_rkRJmw_0l5gE2XQ?pwd=2uyu 提取码：2uyu 找不到原作者的帖子了 这个是我的分享链接 在 2023-12-11 15:08:32，"mj-github-github" ***@***.***> 写道： 我后面下载了一份别人解压好的数据进行运行的 在 2023-11-27 17:35:12，"kaixuan" @.> 写道： 您好，我下载了处理好的数据集结构如下： binary/lrs3 ├── sizes_train.npy ├── sizes_val.npy ├── spk_id2spk_idx.npy ├── train.data └── val.data 没有 stats.npy 这个文件，这是否表明我下的文件有损坏=w= 我也是这样，请问你可以后面可以运行吗 我也是这样，请问你可以后面可以运行吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> @Guoxni Hello, 可以帮忙给个缺失文件的下载链接吗？我不知道从哪里下载 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>
  
您好，进去后显示链接失效了，您那里还有这个数据吗？我的邮箱：755764434@qq.com

**Comment by Guoxni** [comment]
链接已发送到邮箱



在 2024-10-29 17:13:52，"Jiaaaaaqwe" ***@***.***> 写道：

链接：https://pan.baidu.com/s/1OyYlC0_rkRJmw_0l5gE2XQ?pwd=2uyu 提取码：2uyu 找不到原作者的帖子了 这个是我的分享链接 在 2023-12-11 15:08:32，"mj-github-github" @.> 写道： 我后面下载了一份别人解压好的数据进行运行的 在 2023-11-27 17:35:12，"kaixuan" @.> 写道： 您好，我下载了处理好的数据集结构如下： binary/lrs3 ├── sizes_train.npy ├── sizes_val.npy ├── spk_id2spk_idx.npy ├── train.data └── val.data 没有 stats.npy 这个文件，这是否表明我下的文件有损坏=w= 我也是这样，请问你可以后面可以运行吗 我也是这样，请问你可以后面可以运行吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> @Guoxni Hello, 可以帮忙给个缺失文件的下载链接吗？我不知道从哪里下载 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.>

***@***.***

**Comment by cauthiny** [comment]
> 链接已发送到邮箱
> 
> 
> 
> 在 2024-10-29 17:13:52，"Jiaaaaaqwe" ***@***.***> 写道：
> 
> 链接：https://pan.baidu.com/s/1OyYlC0_rkRJmw_0l5gE2XQ?pwd=2uyu 提取码：2uyu 找不到原作者的帖子了 这个是我的分享链接 在 2023-12-11 15:08:32，"mj-github-github" @.> 写道： 我后面下载了一份别人解压好的数据进行运行的 在 2023-11-27 17:35:12，"kaixuan" @.> 写道： 您好，我下载了处理好的数据集结构如下： binary/lrs3 ├── sizes_train.npy ├── sizes_val.npy ├── spk_id2spk_idx.npy ├── train.data └── val.data 没有 stats.npy 这个文件，这是否表明我下的文件有损坏=w= 我也是这样，请问你可以后面可以运行吗 我也是这样，请问你可以后面可以运行吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> [@Guoxni](https://github.com/Guoxni) Hello, 可以帮忙给个缺失文件的下载链接吗？我不知道从哪里下载 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.>
> 
> ***@***.***
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

你好，请问这个文件是LRS3原本的数据集吗，我在寻找能下载原始数据集的地方，但是官网的已经不能打开。请问有途径可以下载吗？
