### ISSUE TITLE
AssertionError: | ckpt not found in checkpoints/lrs3/lm3d_vae/.

### ISSUE THREAD

**Issue by GregoryZeng** [yerfor/GeneFace#81]
This is a excellent project for a novice like me!
I am following the training guide [docs](https://github.com/yerfor/GeneFace/tree/main/docs/train_models) until the step3 (postnet training). 

I run this command for `Lieu` example: `python tasks/run.py --config=egs/datasets/videos/Lieu/lm3d_postnet_sync.yaml --exp_name=checkpoints/Lieu/postnet` and get the error below. However, I did run this command without error for the `May` example.

```
checkpoints/lrs3/syncnet 40000
| load 'model' from 'checkpoints/lrs3/syncnet/model_ckpt_steps_40000.ckpt'.
checkpoints/lrs3/lm3d_vae/ 40000
Traceback (most recent call last):
  File "/root/GeneFace/tasks/run.py", line 20, in <module>
    run_task()
  File "/root/GeneFace/tasks/run.py", line 14, in run_task
    task_cls.start()
  File "/root/GeneFace/utils/commons/base_task.py", line 251, in start
    trainer.fit(cls)
  File "/root/GeneFace/utils/commons/trainer.py", line 120, in fit
    self.task = task_cls()
  File "/root/GeneFace/tasks/postnet/lm3d_postnet_adv_sync.py", line 22, in __init__
    self.audio2motion_task = self.build_audio2motion_task()
  File "/root/GeneFace/tasks/postnet/lm3d_postnet_adv_sync.py", line 37, in build_audio2motion_task
    load_ckpt(self.audio2motion_task.model, audio2motion_work_dir, 'model', steps=audio2motion_ckpt_steps)
  File "/root/GeneFace/utils/commons/ckpt_utils.py", line 65, in load_ckpt
    assert False, e_msg
AssertionError: | ckpt not found in checkpoints/lrs3/lm3d_vae/.
```
I have searched globally for `lm3d_vae` but I do not find relevant config and every strings matched are `lm3d_vae_sync`. What could be the problem? I appreciate your help.

**Comment by JamesLong199** [comment]
It seems like the a hyperparameter is determined by the first config file that explicitly mentions it, rather than the last config file in the chain. 

For example, in "egs/egs_bases/postnet/base.yaml" the parameter "audio2motion_work_dir" is set to "checkpoints/lrs3/lm3d_vae/", and it doesn't work when I try to reset this parameter to "checkpoints/lrs3/lm3d_vae_sync/" in "egs/datasets/videos/Macron/lm3d_postnet_sync.yaml". By that I mean the parameter value is still "checkpoints/lrs3/lm3d_vae/".

I was wondering if it is designed this way intentionally or it should be fixed. 

Overall it is a great repo!
