### ISSUE TITLE
Renderer Issue

### ISSUE THREAD

**Issue by G-1nOnly** [yerfor/GeneFace#96]
Hello ! Thanks for such a great work and congratulations on being accepted by ICLR2023.

I've run your code for a customized dataset and found out that the lip does not match the audio as well as the demo video. I have visualized the landmark and found out that the landmark matches the audio, so I think it is a renderer issue. I'm currently using the radnerf renderer, do you have any suggestions on solving this issue? 

Thanks in advance!

**Comment by yerfor** [comment]
hi，how about the video length? It may need 3-5 minutes to learn a good tenderer. By the way, a learning curve about your head_nerf may help me find out the problem.

**Comment by G-1nOnly** [comment]
Thanks, the video length is over 4 minutes, and the learning curve is provided as follows. 

<img width="766" alt="1" src="https://user-images.githubusercontent.com/64891841/230824582-383c8612-4a50-4197-ae92-a9cb9346257e.png">
<img width="761" alt="2" src="https://user-images.githubusercontent.com/64891841/230824594-57f2c61c-eadf-4b7d-a7f3-60d9e3f854f2.png">
<img width="590" alt="3" src="https://user-images.githubusercontent.com/64891841/230824603-f7633d9f-3bfe-40aa-b63e-1f455eead209.png">

Thanks in advance!

**Comment by yerfor** [comment]
Hi, it seems that the adversarial training of postnet has failed (the confidence of discriminator to the generate sample is only around 0.3, which ideally should be 0.5). I have two suggestions:

1) try lm3d_vae_sync_pitch and lm3d_postnet_sync_pitch. Because we found pitch is a useful hint for the postnet to successfully perform the domain adaptation.

2) reduce the number of layers in discriminator, which may ease the adversarial training.

**Comment by yerfor** [comment]
Hi, I notice that you closed this issuse as completed. Can you feedback is you problem solved? And which method helps you out?
